// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/wso2/aep/aep-api/internal/clients/openchoreo"
	"github.com/wso2/aep/aep-api/internal/gen"
)

// Ensure, that ComponentClientMock does implement openchoreo.ComponentClient.
// If this is not the case, regenerate this file with moq.
var _ openchoreo.ComponentClient = &ComponentClientMock{}

// ComponentClientMock is a mock implementation of openchoreo.ComponentClient.
//
//	func TestSomethingThatUsesComponentClient(t *testing.T) {
//
//		// make and configure a mocked openchoreo.ComponentClient
//		mockedComponentClient := &ComponentClientMock{
//			CreateComponentFunc: func(ctx context.Context, orgName string, projectName string, req *openchoreo.CreateComponentRequest) (*gen.Component, error) {
//				panic("mock out the CreateComponent method")
//			},
//			DeleteComponentFunc: func(ctx context.Context, orgName string, projectName string, componentName string) error {
//				panic("mock out the DeleteComponent method")
//			},
//			GetComponentFunc: func(ctx context.Context, orgName string, projectName string, componentName string) (*gen.Component, error) {
//				panic("mock out the GetComponent method")
//			},
//			GetWorkflowRunFunc: func(ctx context.Context, orgName string, runName string) (*gen.WorkflowRun, error) {
//				panic("mock out the GetWorkflowRun method")
//			},
//			ListComponentsFunc: func(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*gen.ComponentList, error) {
//				panic("mock out the ListComponents method")
//			},
//			ListDeploymentsFunc: func(ctx context.Context, orgName string, projectName string, componentName string) (*gen.DeploymentList, error) {
//				panic("mock out the ListDeployments method")
//			},
//			ListProjectReleaseBindingsFunc: func(ctx context.Context, orgName string, projectName string) ([]openchoreo.ReleaseBindingSummary, error) {
//				panic("mock out the ListProjectReleaseBindings method")
//			},
//			ListProjectWorkflowRunsFunc: func(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*gen.WorkflowRunList, error) {
//				panic("mock out the ListProjectWorkflowRuns method")
//			},
//			ListWorkflowRunsFunc: func(ctx context.Context, orgName string, projectName string, componentName string, limit int, cursor string) (*gen.WorkflowRunList, error) {
//				panic("mock out the ListWorkflowRuns method")
//			},
//			TriggerBuildFunc: func(ctx context.Context, orgName string, projectName string, componentName string, secretRef string, runName string) (*gen.WorkflowRun, error) {
//				panic("mock out the TriggerBuild method")
//			},
//			TriggerBuildAtCommitFunc: func(ctx context.Context, orgName string, projectName string, componentName string, commitSHA string, secretRef string, runName string) (*gen.WorkflowRun, error) {
//				panic("mock out the TriggerBuildAtCommit method")
//			},
//			TriggerCodingAgentFunc: func(ctx context.Context, params openchoreo.CodingAgentParams) (*gen.WorkflowRun, error) {
//				panic("mock out the TriggerCodingAgent method")
//			},
//			UpdateComponentTraitEnvironmentConfigsFunc: func(ctx context.Context, orgName string, projectName string, componentName string, configs map[string]map[string]interface{}) error {
//				panic("mock out the UpdateComponentTraitEnvironmentConfigs method")
//			},
//			UpdateComponentTraitsFunc: func(ctx context.Context, orgName string, projectName string, componentName string, traits []openchoreo.ComponentTrait) error {
//				panic("mock out the UpdateComponentTraits method")
//			},
//			UpdateComponentWorkflowEnvVarsFunc: func(ctx context.Context, orgName string, projectName string, componentName string, envVars []openchoreo.WorkflowEnvVarRef) error {
//				panic("mock out the UpdateComponentWorkflowEnvVars method")
//			},
//			UpdateComponentWorkflowFilesFunc: func(ctx context.Context, orgName string, projectName string, componentName string, files []openchoreo.WorkflowFileVar) error {
//				panic("mock out the UpdateComponentWorkflowFiles method")
//			},
//		}
//
//		// use mockedComponentClient in code that requires openchoreo.ComponentClient
//		// and then make assertions.
//
//	}
type ComponentClientMock struct {
	// CreateComponentFunc mocks the CreateComponent method.
	CreateComponentFunc func(ctx context.Context, orgName string, projectName string, req *openchoreo.CreateComponentRequest) (*gen.Component, error)

	// DeleteComponentFunc mocks the DeleteComponent method.
	DeleteComponentFunc func(ctx context.Context, orgName string, projectName string, componentName string) error

	// GetComponentFunc mocks the GetComponent method.
	GetComponentFunc func(ctx context.Context, orgName string, projectName string, componentName string) (*gen.Component, error)

	// GetWorkflowRunFunc mocks the GetWorkflowRun method.
	GetWorkflowRunFunc func(ctx context.Context, orgName string, runName string) (*gen.WorkflowRun, error)

	// ListComponentsFunc mocks the ListComponents method.
	ListComponentsFunc func(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*gen.ComponentList, error)

	// ListDeploymentsFunc mocks the ListDeployments method.
	ListDeploymentsFunc func(ctx context.Context, orgName string, projectName string, componentName string) (*gen.DeploymentList, error)

	// ListProjectReleaseBindingsFunc mocks the ListProjectReleaseBindings method.
	ListProjectReleaseBindingsFunc func(ctx context.Context, orgName string, projectName string) ([]openchoreo.ReleaseBindingSummary, error)

	// ListProjectWorkflowRunsFunc mocks the ListProjectWorkflowRuns method.
	ListProjectWorkflowRunsFunc func(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*gen.WorkflowRunList, error)

	// ListWorkflowRunsFunc mocks the ListWorkflowRuns method.
	ListWorkflowRunsFunc func(ctx context.Context, orgName string, projectName string, componentName string, limit int, cursor string) (*gen.WorkflowRunList, error)

	// TriggerBuildFunc mocks the TriggerBuild method.
	TriggerBuildFunc func(ctx context.Context, orgName string, projectName string, componentName string, secretRef string, runName string) (*gen.WorkflowRun, error)

	// TriggerBuildAtCommitFunc mocks the TriggerBuildAtCommit method.
	TriggerBuildAtCommitFunc func(ctx context.Context, orgName string, projectName string, componentName string, commitSHA string, secretRef string, runName string) (*gen.WorkflowRun, error)

	// TriggerCodingAgentFunc mocks the TriggerCodingAgent method.
	TriggerCodingAgentFunc func(ctx context.Context, params openchoreo.CodingAgentParams) (*gen.WorkflowRun, error)

	// UpdateComponentTraitEnvironmentConfigsFunc mocks the UpdateComponentTraitEnvironmentConfigs method.
	UpdateComponentTraitEnvironmentConfigsFunc func(ctx context.Context, orgName string, projectName string, componentName string, configs map[string]map[string]interface{}) error

	// UpdateComponentTraitsFunc mocks the UpdateComponentTraits method.
	UpdateComponentTraitsFunc func(ctx context.Context, orgName string, projectName string, componentName string, traits []openchoreo.ComponentTrait) error

	// UpdateComponentWorkflowEnvVarsFunc mocks the UpdateComponentWorkflowEnvVars method.
	UpdateComponentWorkflowEnvVarsFunc func(ctx context.Context, orgName string, projectName string, componentName string, envVars []openchoreo.WorkflowEnvVarRef) error

	// UpdateComponentWorkflowFilesFunc mocks the UpdateComponentWorkflowFiles method.
	UpdateComponentWorkflowFilesFunc func(ctx context.Context, orgName string, projectName string, componentName string, files []openchoreo.WorkflowFileVar) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateComponent holds details about calls to the CreateComponent method.
		CreateComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// Req is the req argument value.
			Req *openchoreo.CreateComponentRequest
		}
		// DeleteComponent holds details about calls to the DeleteComponent method.
		DeleteComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// GetComponent holds details about calls to the GetComponent method.
		GetComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// GetWorkflowRun holds details about calls to the GetWorkflowRun method.
		GetWorkflowRun []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// RunName is the runName argument value.
			RunName string
		}
		// ListComponents holds details about calls to the ListComponents method.
		ListComponents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// Limit is the limit argument value.
			Limit int
			// Cursor is the cursor argument value.
			Cursor string
		}
		// ListDeployments holds details about calls to the ListDeployments method.
		ListDeployments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// ListProjectReleaseBindings holds details about calls to the ListProjectReleaseBindings method.
		ListProjectReleaseBindings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
		}
		// ListProjectWorkflowRuns holds details about calls to the ListProjectWorkflowRuns method.
		ListProjectWorkflowRuns []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// Limit is the limit argument value.
			Limit int
			// Cursor is the cursor argument value.
			Cursor string
		}
		// ListWorkflowRuns holds details about calls to the ListWorkflowRuns method.
		ListWorkflowRuns []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// Limit is the limit argument value.
			Limit int
			// Cursor is the cursor argument value.
			Cursor string
		}
		// TriggerBuild holds details about calls to the TriggerBuild method.
		TriggerBuild []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// SecretRef is the secretRef argument value.
			SecretRef string
			// RunName is the runName argument value.
			RunName string
		}
		// TriggerBuildAtCommit holds details about calls to the TriggerBuildAtCommit method.
		TriggerBuildAtCommit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// CommitSHA is the commitSHA argument value.
			CommitSHA string
			// SecretRef is the secretRef argument value.
			SecretRef string
			// RunName is the runName argument value.
			RunName string
		}
		// TriggerCodingAgent holds details about calls to the TriggerCodingAgent method.
		TriggerCodingAgent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params openchoreo.CodingAgentParams
		}
		// UpdateComponentTraitEnvironmentConfigs holds details about calls to the UpdateComponentTraitEnvironmentConfigs method.
		UpdateComponentTraitEnvironmentConfigs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// Configs is the configs argument value.
			Configs map[string]map[string]interface{}
		}
		// UpdateComponentTraits holds details about calls to the UpdateComponentTraits method.
		UpdateComponentTraits []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// Traits is the traits argument value.
			Traits []openchoreo.ComponentTrait
		}
		// UpdateComponentWorkflowEnvVars holds details about calls to the UpdateComponentWorkflowEnvVars method.
		UpdateComponentWorkflowEnvVars []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// EnvVars is the envVars argument value.
			EnvVars []openchoreo.WorkflowEnvVarRef
		}
		// UpdateComponentWorkflowFiles holds details about calls to the UpdateComponentWorkflowFiles method.
		UpdateComponentWorkflowFiles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// Files is the files argument value.
			Files []openchoreo.WorkflowFileVar
		}
	}
	lockCreateComponent                        sync.RWMutex
	lockDeleteComponent                        sync.RWMutex
	lockGetComponent                           sync.RWMutex
	lockGetWorkflowRun                         sync.RWMutex
	lockListComponents                         sync.RWMutex
	lockListDeployments                        sync.RWMutex
	lockListProjectReleaseBindings             sync.RWMutex
	lockListProjectWorkflowRuns                sync.RWMutex
	lockListWorkflowRuns                       sync.RWMutex
	lockTriggerBuild                           sync.RWMutex
	lockTriggerBuildAtCommit                   sync.RWMutex
	lockTriggerCodingAgent                     sync.RWMutex
	lockUpdateComponentTraitEnvironmentConfigs sync.RWMutex
	lockUpdateComponentTraits                  sync.RWMutex
	lockUpdateComponentWorkflowEnvVars         sync.RWMutex
	lockUpdateComponentWorkflowFiles           sync.RWMutex
}

// CreateComponent calls CreateComponentFunc.
func (mock *ComponentClientMock) CreateComponent(ctx context.Context, orgName string, projectName string, req *openchoreo.CreateComponentRequest) (*gen.Component, error) {
	if mock.CreateComponentFunc == nil {
		panic("ComponentClientMock.CreateComponentFunc: method is nil but ComponentClient.CreateComponent was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Req         *openchoreo.CreateComponentRequest
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		Req:         req,
	}
	mock.lockCreateComponent.Lock()
	mock.calls.CreateComponent = append(mock.calls.CreateComponent, callInfo)
	mock.lockCreateComponent.Unlock()
	return mock.CreateComponentFunc(ctx, orgName, projectName, req)
}

// CreateComponentCalls gets all the calls that were made to CreateComponent.
// Check the length with:
//
//	len(mockedComponentClient.CreateComponentCalls())
func (mock *ComponentClientMock) CreateComponentCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	Req         *openchoreo.CreateComponentRequest
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Req         *openchoreo.CreateComponentRequest
	}
	mock.lockCreateComponent.RLock()
	calls = mock.calls.CreateComponent
	mock.lockCreateComponent.RUnlock()
	return calls
}

// DeleteComponent calls DeleteComponentFunc.
func (mock *ComponentClientMock) DeleteComponent(ctx context.Context, orgName string, projectName string, componentName string) error {
	if mock.DeleteComponentFunc == nil {
		panic("ComponentClientMock.DeleteComponentFunc: method is nil but ComponentClient.DeleteComponent was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
	}
	mock.lockDeleteComponent.Lock()
	mock.calls.DeleteComponent = append(mock.calls.DeleteComponent, callInfo)
	mock.lockDeleteComponent.Unlock()
	return mock.DeleteComponentFunc(ctx, orgName, projectName, componentName)
}

// DeleteComponentCalls gets all the calls that were made to DeleteComponent.
// Check the length with:
//
//	len(mockedComponentClient.DeleteComponentCalls())
func (mock *ComponentClientMock) DeleteComponentCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}
	mock.lockDeleteComponent.RLock()
	calls = mock.calls.DeleteComponent
	mock.lockDeleteComponent.RUnlock()
	return calls
}

// GetComponent calls GetComponentFunc.
func (mock *ComponentClientMock) GetComponent(ctx context.Context, orgName string, projectName string, componentName string) (*gen.Component, error) {
	if mock.GetComponentFunc == nil {
		panic("ComponentClientMock.GetComponentFunc: method is nil but ComponentClient.GetComponent was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
	}
	mock.lockGetComponent.Lock()
	mock.calls.GetComponent = append(mock.calls.GetComponent, callInfo)
	mock.lockGetComponent.Unlock()
	return mock.GetComponentFunc(ctx, orgName, projectName, componentName)
}

// GetComponentCalls gets all the calls that were made to GetComponent.
// Check the length with:
//
//	len(mockedComponentClient.GetComponentCalls())
func (mock *ComponentClientMock) GetComponentCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}
	mock.lockGetComponent.RLock()
	calls = mock.calls.GetComponent
	mock.lockGetComponent.RUnlock()
	return calls
}

// GetWorkflowRun calls GetWorkflowRunFunc.
func (mock *ComponentClientMock) GetWorkflowRun(ctx context.Context, orgName string, runName string) (*gen.WorkflowRun, error) {
	if mock.GetWorkflowRunFunc == nil {
		panic("ComponentClientMock.GetWorkflowRunFunc: method is nil but ComponentClient.GetWorkflowRun was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
		RunName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
		RunName: runName,
	}
	mock.lockGetWorkflowRun.Lock()
	mock.calls.GetWorkflowRun = append(mock.calls.GetWorkflowRun, callInfo)
	mock.lockGetWorkflowRun.Unlock()
	return mock.GetWorkflowRunFunc(ctx, orgName, runName)
}

// GetWorkflowRunCalls gets all the calls that were made to GetWorkflowRun.
// Check the length with:
//
//	len(mockedComponentClient.GetWorkflowRunCalls())
func (mock *ComponentClientMock) GetWorkflowRunCalls() []struct {
	Ctx     context.Context
	OrgName string
	RunName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
		RunName string
	}
	mock.lockGetWorkflowRun.RLock()
	calls = mock.calls.GetWorkflowRun
	mock.lockGetWorkflowRun.RUnlock()
	return calls
}

// ListComponents calls ListComponentsFunc.
func (mock *ComponentClientMock) ListComponents(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*gen.ComponentList, error) {
	if mock.ListComponentsFunc == nil {
		panic("ComponentClientMock.ListComponentsFunc: method is nil but ComponentClient.ListComponents was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Limit       int
		Cursor      string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		Limit:       limit,
		Cursor:      cursor,
	}
	mock.lockListComponents.Lock()
	mock.calls.ListComponents = append(mock.calls.ListComponents, callInfo)
	mock.lockListComponents.Unlock()
	return mock.ListComponentsFunc(ctx, orgName, projectName, limit, cursor)
}

// ListComponentsCalls gets all the calls that were made to ListComponents.
// Check the length with:
//
//	len(mockedComponentClient.ListComponentsCalls())
func (mock *ComponentClientMock) ListComponentsCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	Limit       int
	Cursor      string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Limit       int
		Cursor      string
	}
	mock.lockListComponents.RLock()
	calls = mock.calls.ListComponents
	mock.lockListComponents.RUnlock()
	return calls
}

// ListDeployments calls ListDeploymentsFunc.
func (mock *ComponentClientMock) ListDeployments(ctx context.Context, orgName string, projectName string, componentName string) (*gen.DeploymentList, error) {
	if mock.ListDeploymentsFunc == nil {
		panic("ComponentClientMock.ListDeploymentsFunc: method is nil but ComponentClient.ListDeployments was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
	}
	mock.lockListDeployments.Lock()
	mock.calls.ListDeployments = append(mock.calls.ListDeployments, callInfo)
	mock.lockListDeployments.Unlock()
	return mock.ListDeploymentsFunc(ctx, orgName, projectName, componentName)
}

// ListDeploymentsCalls gets all the calls that were made to ListDeployments.
// Check the length with:
//
//	len(mockedComponentClient.ListDeploymentsCalls())
func (mock *ComponentClientMock) ListDeploymentsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}
	mock.lockListDeployments.RLock()
	calls = mock.calls.ListDeployments
	mock.lockListDeployments.RUnlock()
	return calls
}

// ListProjectReleaseBindings calls ListProjectReleaseBindingsFunc.
func (mock *ComponentClientMock) ListProjectReleaseBindings(ctx context.Context, orgName string, projectName string) ([]openchoreo.ReleaseBindingSummary, error) {
	if mock.ListProjectReleaseBindingsFunc == nil {
		panic("ComponentClientMock.ListProjectReleaseBindingsFunc: method is nil but ComponentClient.ListProjectReleaseBindings was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
	}
	mock.lockListProjectReleaseBindings.Lock()
	mock.calls.ListProjectReleaseBindings = append(mock.calls.ListProjectReleaseBindings, callInfo)
	mock.lockListProjectReleaseBindings.Unlock()
	return mock.ListProjectReleaseBindingsFunc(ctx, orgName, projectName)
}

// ListProjectReleaseBindingsCalls gets all the calls that were made to ListProjectReleaseBindings.
// Check the length with:
//
//	len(mockedComponentClient.ListProjectReleaseBindingsCalls())
func (mock *ComponentClientMock) ListProjectReleaseBindingsCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}
	mock.lockListProjectReleaseBindings.RLock()
	calls = mock.calls.ListProjectReleaseBindings
	mock.lockListProjectReleaseBindings.RUnlock()
	return calls
}

// ListProjectWorkflowRuns calls ListProjectWorkflowRunsFunc.
func (mock *ComponentClientMock) ListProjectWorkflowRuns(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*gen.WorkflowRunList, error) {
	if mock.ListProjectWorkflowRunsFunc == nil {
		panic("ComponentClientMock.ListProjectWorkflowRunsFunc: method is nil but ComponentClient.ListProjectWorkflowRuns was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Limit       int
		Cursor      string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		Limit:       limit,
		Cursor:      cursor,
	}
	mock.lockListProjectWorkflowRuns.Lock()
	mock.calls.ListProjectWorkflowRuns = append(mock.calls.ListProjectWorkflowRuns, callInfo)
	mock.lockListProjectWorkflowRuns.Unlock()
	return mock.ListProjectWorkflowRunsFunc(ctx, orgName, projectName, limit, cursor)
}

// ListProjectWorkflowRunsCalls gets all the calls that were made to ListProjectWorkflowRuns.
// Check the length with:
//
//	len(mockedComponentClient.ListProjectWorkflowRunsCalls())
func (mock *ComponentClientMock) ListProjectWorkflowRunsCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	Limit       int
	Cursor      string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Limit       int
		Cursor      string
	}
	mock.lockListProjectWorkflowRuns.RLock()
	calls = mock.calls.ListProjectWorkflowRuns
	mock.lockListProjectWorkflowRuns.RUnlock()
	return calls
}

// ListWorkflowRuns calls ListWorkflowRunsFunc.
func (mock *ComponentClientMock) ListWorkflowRuns(ctx context.Context, orgName string, projectName string, componentName string, limit int, cursor string) (*gen.WorkflowRunList, error) {
	if mock.ListWorkflowRunsFunc == nil {
		panic("ComponentClientMock.ListWorkflowRunsFunc: method is nil but ComponentClient.ListWorkflowRuns was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Limit         int
		Cursor        string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		Limit:         limit,
		Cursor:        cursor,
	}
	mock.lockListWorkflowRuns.Lock()
	mock.calls.ListWorkflowRuns = append(mock.calls.ListWorkflowRuns, callInfo)
	mock.lockListWorkflowRuns.Unlock()
	return mock.ListWorkflowRunsFunc(ctx, orgName, projectName, componentName, limit, cursor)
}

// ListWorkflowRunsCalls gets all the calls that were made to ListWorkflowRuns.
// Check the length with:
//
//	len(mockedComponentClient.ListWorkflowRunsCalls())
func (mock *ComponentClientMock) ListWorkflowRunsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	Limit         int
	Cursor        string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Limit         int
		Cursor        string
	}
	mock.lockListWorkflowRuns.RLock()
	calls = mock.calls.ListWorkflowRuns
	mock.lockListWorkflowRuns.RUnlock()
	return calls
}

// TriggerBuild calls TriggerBuildFunc.
func (mock *ComponentClientMock) TriggerBuild(ctx context.Context, orgName string, projectName string, componentName string, secretRef string, runName string) (*gen.WorkflowRun, error) {
	if mock.TriggerBuildFunc == nil {
		panic("ComponentClientMock.TriggerBuildFunc: method is nil but ComponentClient.TriggerBuild was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		SecretRef     string
		RunName       string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		SecretRef:     secretRef,
		RunName:       runName,
	}
	mock.lockTriggerBuild.Lock()
	mock.calls.TriggerBuild = append(mock.calls.TriggerBuild, callInfo)
	mock.lockTriggerBuild.Unlock()
	return mock.TriggerBuildFunc(ctx, orgName, projectName, componentName, secretRef, runName)
}

// TriggerBuildCalls gets all the calls that were made to TriggerBuild.
// Check the length with:
//
//	len(mockedComponentClient.TriggerBuildCalls())
func (mock *ComponentClientMock) TriggerBuildCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	SecretRef     string
	RunName       string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		SecretRef     string
		RunName       string
	}
	mock.lockTriggerBuild.RLock()
	calls = mock.calls.TriggerBuild
	mock.lockTriggerBuild.RUnlock()
	return calls
}

// TriggerBuildAtCommit calls TriggerBuildAtCommitFunc.
func (mock *ComponentClientMock) TriggerBuildAtCommit(ctx context.Context, orgName string, projectName string, componentName string, commitSHA string, secretRef string, runName string) (*gen.WorkflowRun, error) {
	if mock.TriggerBuildAtCommitFunc == nil {
		panic("ComponentClientMock.TriggerBuildAtCommitFunc: method is nil but ComponentClient.TriggerBuildAtCommit was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		CommitSHA     string
		SecretRef     string
		RunName       string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		CommitSHA:     commitSHA,
		SecretRef:     secretRef,
		RunName:       runName,
	}
	mock.lockTriggerBuildAtCommit.Lock()
	mock.calls.TriggerBuildAtCommit = append(mock.calls.TriggerBuildAtCommit, callInfo)
	mock.lockTriggerBuildAtCommit.Unlock()
	return mock.TriggerBuildAtCommitFunc(ctx, orgName, projectName, componentName, commitSHA, secretRef, runName)
}

// TriggerBuildAtCommitCalls gets all the calls that were made to TriggerBuildAtCommit.
// Check the length with:
//
//	len(mockedComponentClient.TriggerBuildAtCommitCalls())
func (mock *ComponentClientMock) TriggerBuildAtCommitCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	CommitSHA     string
	SecretRef     string
	RunName       string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		CommitSHA     string
		SecretRef     string
		RunName       string
	}
	mock.lockTriggerBuildAtCommit.RLock()
	calls = mock.calls.TriggerBuildAtCommit
	mock.lockTriggerBuildAtCommit.RUnlock()
	return calls
}

// TriggerCodingAgent calls TriggerCodingAgentFunc.
func (mock *ComponentClientMock) TriggerCodingAgent(ctx context.Context, params openchoreo.CodingAgentParams) (*gen.WorkflowRun, error) {
	if mock.TriggerCodingAgentFunc == nil {
		panic("ComponentClientMock.TriggerCodingAgentFunc: method is nil but ComponentClient.TriggerCodingAgent was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params openchoreo.CodingAgentParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockTriggerCodingAgent.Lock()
	mock.calls.TriggerCodingAgent = append(mock.calls.TriggerCodingAgent, callInfo)
	mock.lockTriggerCodingAgent.Unlock()
	return mock.TriggerCodingAgentFunc(ctx, params)
}

// TriggerCodingAgentCalls gets all the calls that were made to TriggerCodingAgent.
// Check the length with:
//
//	len(mockedComponentClient.TriggerCodingAgentCalls())
func (mock *ComponentClientMock) TriggerCodingAgentCalls() []struct {
	Ctx    context.Context
	Params openchoreo.CodingAgentParams
} {
	var calls []struct {
		Ctx    context.Context
		Params openchoreo.CodingAgentParams
	}
	mock.lockTriggerCodingAgent.RLock()
	calls = mock.calls.TriggerCodingAgent
	mock.lockTriggerCodingAgent.RUnlock()
	return calls
}

// UpdateComponentTraitEnvironmentConfigs calls UpdateComponentTraitEnvironmentConfigsFunc.
func (mock *ComponentClientMock) UpdateComponentTraitEnvironmentConfigs(ctx context.Context, orgName string, projectName string, componentName string, configs map[string]map[string]interface{}) error {
	if mock.UpdateComponentTraitEnvironmentConfigsFunc == nil {
		panic("ComponentClientMock.UpdateComponentTraitEnvironmentConfigsFunc: method is nil but ComponentClient.UpdateComponentTraitEnvironmentConfigs was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Configs       map[string]map[string]interface{}
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		Configs:       configs,
	}
	mock.lockUpdateComponentTraitEnvironmentConfigs.Lock()
	mock.calls.UpdateComponentTraitEnvironmentConfigs = append(mock.calls.UpdateComponentTraitEnvironmentConfigs, callInfo)
	mock.lockUpdateComponentTraitEnvironmentConfigs.Unlock()
	return mock.UpdateComponentTraitEnvironmentConfigsFunc(ctx, orgName, projectName, componentName, configs)
}

// UpdateComponentTraitEnvironmentConfigsCalls gets all the calls that were made to UpdateComponentTraitEnvironmentConfigs.
// Check the length with:
//
//	len(mockedComponentClient.UpdateComponentTraitEnvironmentConfigsCalls())
func (mock *ComponentClientMock) UpdateComponentTraitEnvironmentConfigsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	Configs       map[string]map[string]interface{}
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Configs       map[string]map[string]interface{}
	}
	mock.lockUpdateComponentTraitEnvironmentConfigs.RLock()
	calls = mock.calls.UpdateComponentTraitEnvironmentConfigs
	mock.lockUpdateComponentTraitEnvironmentConfigs.RUnlock()
	return calls
}

// UpdateComponentTraits calls UpdateComponentTraitsFunc.
func (mock *ComponentClientMock) UpdateComponentTraits(ctx context.Context, orgName string, projectName string, componentName string, traits []openchoreo.ComponentTrait) error {
	if mock.UpdateComponentTraitsFunc == nil {
		panic("ComponentClientMock.UpdateComponentTraitsFunc: method is nil but ComponentClient.UpdateComponentTraits was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Traits        []openchoreo.ComponentTrait
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		Traits:        traits,
	}
	mock.lockUpdateComponentTraits.Lock()
	mock.calls.UpdateComponentTraits = append(mock.calls.UpdateComponentTraits, callInfo)
	mock.lockUpdateComponentTraits.Unlock()
	return mock.UpdateComponentTraitsFunc(ctx, orgName, projectName, componentName, traits)
}

// UpdateComponentTraitsCalls gets all the calls that were made to UpdateComponentTraits.
// Check the length with:
//
//	len(mockedComponentClient.UpdateComponentTraitsCalls())
func (mock *ComponentClientMock) UpdateComponentTraitsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	Traits        []openchoreo.ComponentTrait
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Traits        []openchoreo.ComponentTrait
	}
	mock.lockUpdateComponentTraits.RLock()
	calls = mock.calls.UpdateComponentTraits
	mock.lockUpdateComponentTraits.RUnlock()
	return calls
}

// UpdateComponentWorkflowEnvVars calls UpdateComponentWorkflowEnvVarsFunc.
func (mock *ComponentClientMock) UpdateComponentWorkflowEnvVars(ctx context.Context, orgName string, projectName string, componentName string, envVars []openchoreo.WorkflowEnvVarRef) error {
	if mock.UpdateComponentWorkflowEnvVarsFunc == nil {
		panic("ComponentClientMock.UpdateComponentWorkflowEnvVarsFunc: method is nil but ComponentClient.UpdateComponentWorkflowEnvVars was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		EnvVars       []openchoreo.WorkflowEnvVarRef
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		EnvVars:       envVars,
	}
	mock.lockUpdateComponentWorkflowEnvVars.Lock()
	mock.calls.UpdateComponentWorkflowEnvVars = append(mock.calls.UpdateComponentWorkflowEnvVars, callInfo)
	mock.lockUpdateComponentWorkflowEnvVars.Unlock()
	return mock.UpdateComponentWorkflowEnvVarsFunc(ctx, orgName, projectName, componentName, envVars)
}

// UpdateComponentWorkflowEnvVarsCalls gets all the calls that were made to UpdateComponentWorkflowEnvVars.
// Check the length with:
//
//	len(mockedComponentClient.UpdateComponentWorkflowEnvVarsCalls())
func (mock *ComponentClientMock) UpdateComponentWorkflowEnvVarsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	EnvVars       []openchoreo.WorkflowEnvVarRef
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		EnvVars       []openchoreo.WorkflowEnvVarRef
	}
	mock.lockUpdateComponentWorkflowEnvVars.RLock()
	calls = mock.calls.UpdateComponentWorkflowEnvVars
	mock.lockUpdateComponentWorkflowEnvVars.RUnlock()
	return calls
}

// UpdateComponentWorkflowFiles calls UpdateComponentWorkflowFilesFunc.
func (mock *ComponentClientMock) UpdateComponentWorkflowFiles(ctx context.Context, orgName string, projectName string, componentName string, files []openchoreo.WorkflowFileVar) error {
	if mock.UpdateComponentWorkflowFilesFunc == nil {
		panic("ComponentClientMock.UpdateComponentWorkflowFilesFunc: method is nil but ComponentClient.UpdateComponentWorkflowFiles was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Files         []openchoreo.WorkflowFileVar
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		Files:         files,
	}
	mock.lockUpdateComponentWorkflowFiles.Lock()
	mock.calls.UpdateComponentWorkflowFiles = append(mock.calls.UpdateComponentWorkflowFiles, callInfo)
	mock.lockUpdateComponentWorkflowFiles.Unlock()
	return mock.UpdateComponentWorkflowFilesFunc(ctx, orgName, projectName, componentName, files)
}

// UpdateComponentWorkflowFilesCalls gets all the calls that were made to UpdateComponentWorkflowFiles.
// Check the length with:
//
//	len(mockedComponentClient.UpdateComponentWorkflowFilesCalls())
func (mock *ComponentClientMock) UpdateComponentWorkflowFilesCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	Files         []openchoreo.WorkflowFileVar
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Files         []openchoreo.WorkflowFileVar
	}
	mock.lockUpdateComponentWorkflowFiles.RLock()
	calls = mock.calls.UpdateComponentWorkflowFiles
	mock.lockUpdateComponentWorkflowFiles.RUnlock()
	return calls
}
