// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/wso2/aep/aep-api/internal/clients/openchoreo"
	"github.com/wso2/aep/aep-api/internal/gen"
)

// Ensure, that NamespaceClientMock does implement openchoreo.NamespaceClient.
// If this is not the case, regenerate this file with moq.
var _ openchoreo.NamespaceClient = &NamespaceClientMock{}

// NamespaceClientMock is a mock implementation of openchoreo.NamespaceClient.
//
//	func TestSomethingThatUsesNamespaceClient(t *testing.T) {
//
//		// make and configure a mocked openchoreo.NamespaceClient
//		mockedNamespaceClient := &NamespaceClientMock{
//			GetNamespaceFunc: func(ctx context.Context, name string) (*gen.OrganizationView, error) {
//				panic("mock out the GetNamespace method")
//			},
//			ListNamespacesFunc: func(ctx context.Context) ([]gen.OrganizationView, error) {
//				panic("mock out the ListNamespaces method")
//			},
//		}
//
//		// use mockedNamespaceClient in code that requires openchoreo.NamespaceClient
//		// and then make assertions.
//
//	}
type NamespaceClientMock struct {
	// GetNamespaceFunc mocks the GetNamespace method.
	GetNamespaceFunc func(ctx context.Context, name string) (*gen.OrganizationView, error)

	// ListNamespacesFunc mocks the ListNamespaces method.
	ListNamespacesFunc func(ctx context.Context) ([]gen.OrganizationView, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetNamespace holds details about calls to the GetNamespace method.
		GetNamespace []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// ListNamespaces holds details about calls to the ListNamespaces method.
		ListNamespaces []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGetNamespace   sync.RWMutex
	lockListNamespaces sync.RWMutex
}

// GetNamespace calls GetNamespaceFunc.
func (mock *NamespaceClientMock) GetNamespace(ctx context.Context, name string) (*gen.OrganizationView, error) {
	if mock.GetNamespaceFunc == nil {
		panic("NamespaceClientMock.GetNamespaceFunc: method is nil but NamespaceClient.GetNamespace was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetNamespace.Lock()
	mock.calls.GetNamespace = append(mock.calls.GetNamespace, callInfo)
	mock.lockGetNamespace.Unlock()
	return mock.GetNamespaceFunc(ctx, name)
}

// GetNamespaceCalls gets all the calls that were made to GetNamespace.
// Check the length with:
//
//	len(mockedNamespaceClient.GetNamespaceCalls())
func (mock *NamespaceClientMock) GetNamespaceCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetNamespace.RLock()
	calls = mock.calls.GetNamespace
	mock.lockGetNamespace.RUnlock()
	return calls
}

// ListNamespaces calls ListNamespacesFunc.
func (mock *NamespaceClientMock) ListNamespaces(ctx context.Context) ([]gen.OrganizationView, error) {
	if mock.ListNamespacesFunc == nil {
		panic("NamespaceClientMock.ListNamespacesFunc: method is nil but NamespaceClient.ListNamespaces was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListNamespaces.Lock()
	mock.calls.ListNamespaces = append(mock.calls.ListNamespaces, callInfo)
	mock.lockListNamespaces.Unlock()
	return mock.ListNamespacesFunc(ctx)
}

// ListNamespacesCalls gets all the calls that were made to ListNamespaces.
// Check the length with:
//
//	len(mockedNamespaceClient.ListNamespacesCalls())
func (mock *NamespaceClientMock) ListNamespacesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListNamespaces.RLock()
	calls = mock.calls.ListNamespaces
	mock.lockListNamespaces.RUnlock()
	return calls
}
