// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/wso2/aep/aep-api/internal/clients/openchoreo"
	"github.com/wso2/aep/aep-api/internal/gen"
)

// Ensure, that ProjectClientMock does implement openchoreo.ProjectClient.
// If this is not the case, regenerate this file with moq.
var _ openchoreo.ProjectClient = &ProjectClientMock{}

// ProjectClientMock is a mock implementation of openchoreo.ProjectClient.
//
//	func TestSomethingThatUsesProjectClient(t *testing.T) {
//
//		// make and configure a mocked openchoreo.ProjectClient
//		mockedProjectClient := &ProjectClientMock{
//			CreateProjectFunc: func(ctx context.Context, orgName string, req *gen.CreateProjectRequest) (*gen.Project, error) {
//				panic("mock out the CreateProject method")
//			},
//			DeleteProjectFunc: func(ctx context.Context, orgName string, projectName string) error {
//				panic("mock out the DeleteProject method")
//			},
//			GetProjectFunc: func(ctx context.Context, orgName string, projectName string) (*gen.Project, error) {
//				panic("mock out the GetProject method")
//			},
//			ListProjectsFunc: func(ctx context.Context, orgName string, limit int, cursor string) (*gen.ProjectList, error) {
//				panic("mock out the ListProjects method")
//			},
//		}
//
//		// use mockedProjectClient in code that requires openchoreo.ProjectClient
//		// and then make assertions.
//
//	}
type ProjectClientMock struct {
	// CreateProjectFunc mocks the CreateProject method.
	CreateProjectFunc func(ctx context.Context, orgName string, req *gen.CreateProjectRequest) (*gen.Project, error)

	// DeleteProjectFunc mocks the DeleteProject method.
	DeleteProjectFunc func(ctx context.Context, orgName string, projectName string) error

	// GetProjectFunc mocks the GetProject method.
	GetProjectFunc func(ctx context.Context, orgName string, projectName string) (*gen.Project, error)

	// ListProjectsFunc mocks the ListProjects method.
	ListProjectsFunc func(ctx context.Context, orgName string, limit int, cursor string) (*gen.ProjectList, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateProject holds details about calls to the CreateProject method.
		CreateProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// Req is the req argument value.
			Req *gen.CreateProjectRequest
		}
		// DeleteProject holds details about calls to the DeleteProject method.
		DeleteProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
		}
		// GetProject holds details about calls to the GetProject method.
		GetProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
		}
		// ListProjects holds details about calls to the ListProjects method.
		ListProjects []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// Limit is the limit argument value.
			Limit int
			// Cursor is the cursor argument value.
			Cursor string
		}
	}
	lockCreateProject sync.RWMutex
	lockDeleteProject sync.RWMutex
	lockGetProject    sync.RWMutex
	lockListProjects  sync.RWMutex
}

// CreateProject calls CreateProjectFunc.
func (mock *ProjectClientMock) CreateProject(ctx context.Context, orgName string, req *gen.CreateProjectRequest) (*gen.Project, error) {
	if mock.CreateProjectFunc == nil {
		panic("ProjectClientMock.CreateProjectFunc: method is nil but ProjectClient.CreateProject was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
		Req     *gen.CreateProjectRequest
	}{
		Ctx:     ctx,
		OrgName: orgName,
		Req:     req,
	}
	mock.lockCreateProject.Lock()
	mock.calls.CreateProject = append(mock.calls.CreateProject, callInfo)
	mock.lockCreateProject.Unlock()
	return mock.CreateProjectFunc(ctx, orgName, req)
}

// CreateProjectCalls gets all the calls that were made to CreateProject.
// Check the length with:
//
//	len(mockedProjectClient.CreateProjectCalls())
func (mock *ProjectClientMock) CreateProjectCalls() []struct {
	Ctx     context.Context
	OrgName string
	Req     *gen.CreateProjectRequest
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
		Req     *gen.CreateProjectRequest
	}
	mock.lockCreateProject.RLock()
	calls = mock.calls.CreateProject
	mock.lockCreateProject.RUnlock()
	return calls
}

// DeleteProject calls DeleteProjectFunc.
func (mock *ProjectClientMock) DeleteProject(ctx context.Context, orgName string, projectName string) error {
	if mock.DeleteProjectFunc == nil {
		panic("ProjectClientMock.DeleteProjectFunc: method is nil but ProjectClient.DeleteProject was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
	}
	mock.lockDeleteProject.Lock()
	mock.calls.DeleteProject = append(mock.calls.DeleteProject, callInfo)
	mock.lockDeleteProject.Unlock()
	return mock.DeleteProjectFunc(ctx, orgName, projectName)
}

// DeleteProjectCalls gets all the calls that were made to DeleteProject.
// Check the length with:
//
//	len(mockedProjectClient.DeleteProjectCalls())
func (mock *ProjectClientMock) DeleteProjectCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}
	mock.lockDeleteProject.RLock()
	calls = mock.calls.DeleteProject
	mock.lockDeleteProject.RUnlock()
	return calls
}

// GetProject calls GetProjectFunc.
func (mock *ProjectClientMock) GetProject(ctx context.Context, orgName string, projectName string) (*gen.Project, error) {
	if mock.GetProjectFunc == nil {
		panic("ProjectClientMock.GetProjectFunc: method is nil but ProjectClient.GetProject was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
	}
	mock.lockGetProject.Lock()
	mock.calls.GetProject = append(mock.calls.GetProject, callInfo)
	mock.lockGetProject.Unlock()
	return mock.GetProjectFunc(ctx, orgName, projectName)
}

// GetProjectCalls gets all the calls that were made to GetProject.
// Check the length with:
//
//	len(mockedProjectClient.GetProjectCalls())
func (mock *ProjectClientMock) GetProjectCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}
	mock.lockGetProject.RLock()
	calls = mock.calls.GetProject
	mock.lockGetProject.RUnlock()
	return calls
}

// ListProjects calls ListProjectsFunc.
func (mock *ProjectClientMock) ListProjects(ctx context.Context, orgName string, limit int, cursor string) (*gen.ProjectList, error) {
	if mock.ListProjectsFunc == nil {
		panic("ProjectClientMock.ListProjectsFunc: method is nil but ProjectClient.ListProjects was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
		Limit   int
		Cursor  string
	}{
		Ctx:     ctx,
		OrgName: orgName,
		Limit:   limit,
		Cursor:  cursor,
	}
	mock.lockListProjects.Lock()
	mock.calls.ListProjects = append(mock.calls.ListProjects, callInfo)
	mock.lockListProjects.Unlock()
	return mock.ListProjectsFunc(ctx, orgName, limit, cursor)
}

// ListProjectsCalls gets all the calls that were made to ListProjects.
// Check the length with:
//
//	len(mockedProjectClient.ListProjectsCalls())
func (mock *ProjectClientMock) ListProjectsCalls() []struct {
	Ctx     context.Context
	OrgName string
	Limit   int
	Cursor  string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
		Limit   int
		Cursor  string
	}
	mock.lockListProjects.RLock()
	calls = mock.calls.ListProjects
	mock.lockListProjects.RUnlock()
	return calls
}
