apiVersion: v1
kind: Service
metadata:
    name: collab-server
    namespace: {{ .Release.Namespace }}
    labels:
        app: collab-server
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/part-of: wso2-aep
spec:
    selector:
        app: collab-server
    ports:
        - port: {{ .Values.collab.port }}
          targetPort: http
          protocol: TCP
          name: http
    type: ClusterIP
